import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import StoreProvider from "@/redux/StoreProvider";
import "../styles/app.scss"
import localFont from "next/font/local";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Navishkar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoreProvider>
          <Navbar />
          {children}
          <Footer />
          
        </StoreProvider>
      </body>
    </html>
  );
}
